Document: alacritty
Title: Debian alacritty Manual
Author: <insert document author here>
Abstract: This manual describes what alacritty is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/alacritty/alacritty.sgml.gz

Format: postscript
Files: /usr/share/doc/alacritty/alacritty.ps.gz

Format: text
Files: /usr/share/doc/alacritty/alacritty.text.gz

Format: HTML
Index: /usr/share/doc/alacritty/html/index.html
Files: /usr/share/doc/alacritty/html/*.html
